server:
  port: 10010
# 配置路由
zuul:
  routes:
    user-service: /user-service/**
  ignored-services:
    - consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:
  application:
    name: gateway